name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.147.124 -t "
            cd week-25-ci-next-app/ &&
            export NVM_DIR=\$HOME/.nvm &&
            [ -s \$NVM_DIR/nvm.sh ] && source \$NVM_DIR/nvm.sh &&
            nvm use 22.13.1 &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-sever &&
            pm2 restart http-sever &&
            pm2 restart ws-sever
          "
